services:
  # 后端Flask应用服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-mywebsite}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key-change-in-production}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-dev-jwt-secret-change-in-production}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-sk-xxxx}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-3.5-turbo}
      TZ: Asia/Shanghai
    volumes:
      - ./uploads:/app/uploads
    networks:
      - backend_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    # 确保容器启动时uploads目录有正确的权限
    command: >
      sh -c "
        chmod 777 /app/uploads &&
        gunicorn -w 4 -b 0.0.0.0:5000 --worker-class eventlet --worker-connections 1000 --max-requests 1000 --max-requests-jitter 100 --keep-alive 5 --timeout 30 app:app
      "

networks:
  backend_network:
    driver: bridge