name: 前端构建与发布

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: docker.xuanyuan.me/node:22

    steps:
      - name: 检出代码
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          # 确保 git 可用
          if ! command -v git &> /dev/null
          then
              echo "::error::git command not found. Please ensure git is installed in the container."
              apt update && apt install -y git
          fi
          
          # 配置 git 安全目录
          git config --global --add safe.directory "${GITEA_WORKSPACE}"

          # 定义仓库信息
          GITEA_SERVER_URL="https://git.handywote.top"
          GITEA_REPOSITORY="Handy_Wote/MyWebsite"
          
          # 拼接带认证信息的仓库 URL
          REPO_URL="${GITEA_SERVER_URL}/${GITEA_REPOSITORY}.git"
          AUTH_REPO_URL=$(echo "$REPO_URL" | sed "s|://|://gitea-actions:${GITEA_TOKEN}@|")
          
          echo "Cloning repository from ${REPO_URL}..."
          
          # 初始化 git 仓库并克隆代码
          git init
          git remote add origin "${AUTH_REPO_URL}"
          git fetch origin
          
          # 检出指定的分支或标签
          if [ -n "$GITEA_REF_NAME" ]; then
            echo "Checking out branch/tag: ${GITEA_REF_NAME}"
            git checkout "${GITEA_REF_NAME}"
          elif [ -n "$GITEA_SHA" ]; then
            echo "Checking out specific commit: ${GITEA_SHA}"
            git checkout "${GITEA_SHA}"
          else
            echo "Checking out main branch (default)"
            git checkout main || git checkout master
          fi
          
          echo "Source code checked out successfully."

      - name: 调试环境变量
        run: |
          echo "=== Gitea 环境变量 ==="
          echo "GITEA_REF: ${GITEA_REF}"
          echo "GITEA_REF_NAME: ${GITEA_REF_NAME}"
          echo "GITEA_REF_TYPE: ${GITEA_REF_TYPE}"
          echo "GITEA_SHA: ${GITEA_SHA}"
          echo "GITEA_REPOSITORY: ${GITEA_REPOSITORY}"
          echo "GITEA_SERVER_URL: ${GITEA_SERVER_URL}"
          echo "GITEA_EVENT_NAME: ${GITEA_EVENT_NAME}"
          echo "====================="

      - 