name: Sync to GitHub

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  sync-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.email "18666119673@163.com"
          git config --global user.name "Handy_Wote"

      - name: Add GitHub remote
        run: |
          echo "Adding GitHub remote for repo: $GH_REPO"
          git remote add github "https://${GH_TOKEN}@github.com/${GH_REPO}.git"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: ${{ secrets.GH_REPO }}

      - name: Push to GitHub
        run: |
          echo "GITEA_REF: $GITEA_REF"
          # 如果是 tag
          if [[ "$GITEA_REF" == refs/tags/* ]]; then
            TAG_NAME=${GITEA_REF#refs/tags/}
            git push github tag $TAG_NAME
            echo "已同步 tag: $TAG_NAME"
          else
            # 推送分支
            git push github main
            echo "已同步分支: main"
          fi
